### ISSUE TITLE
[IMPROVE] Decrease log level of trace Everything OK 0 requests from INFO to DEBUG

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/fiware-sth-comet#310]
The trace:
{"op":"OPER_STH_SERVER_LOG","time":"2016-04-07T02:11:55.606Z","lvl":"INFO","msg":"Everything OK, 0 requests attended in the last 60s interval"}

Must be printed at log level DEBUG, because not show util information.
One possible utility should be (if need stay in INFO level):
"We have processed X > 0 requests OK. And/Or Y > 0 request with ERROR in the last Z seconds interval" (with Z as a STH parameter)

**Comment by sanchit31** [comment]
hi @cesarjorgemartinez 

My understanding on this issue is : 
1. The trace {"op":"OPER_STH_SERVER_LOG","time":"2016-04-07T02:11:55.606Z","lvl":"INFO","msg":"Everything OK, 0 requests attended in the last 60s interval"} must be printed at log level **DEBUG**. It is currently printed at **INFO** level.
2. A new message needs to be printed at log level **INFO** "We have processed X > 0 requests OK. And/Or Y > 0 request with ERROR in the last Z seconds interval" (with Z as a STH parameter)
where X is the number of attended requests (server KPIs), Y is the number of requests that resulted in ERROR response and Z is the time interval (in seconds) which can be configured as an STH parameter.

Please confirm if my understanding is correct?

I'd like to work on this issue. Please assign it to me.

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/fiware-sth-comet/pull/505
